# Generated by Django 4.2.3 on 2023-07-09 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='产品名称')),
                ('xl_number', models.CharField(max_length=64, verbose_name='新罗编号')),
                ('duw_number', models.CharField(max_length=64, verbose_name='得物编号')),
                ('xz_number', models.CharField(max_length=64, verbose_name='小猪编号')),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Xz_product_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=24, verbose_name='规格')),
                ('xz_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='小猪价格')),
                ('create_time', models.DateField(verbose_name='日期')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xz_name', to='app01.product_number', to_field='name', verbose_name='产品名称')),
            ],
        ),
        migrations.CreateModel(
            name='Duw_product_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=24, verbose_name='规格')),
                ('duw_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='得物价格')),
                ('create_time', models.DateField(verbose_name='日期')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duw_name', to='app01.product_number', to_field='name', verbose_name='产品名称')),
            ],
        ),
    ]
